sudo: required
language: objective-c
osx_image: xcode10.2
before_install:
- npm install -g markdownlint-cli
- npm install -g markdown-link-check
- npm install -g gitbook-cli
- gem install asciidoctor
env:
  global:
    secure: "QiUUbQ9WJKSAxMquDGnSYe2QICwJBK/44vYksIP6b+KTeFwfKmKSWa5B63W9NxGEm1GKQeCnIaplpDw21lB0NKluSkbIAEW7AQfY+txJ3VFIf+DHs3Gid+fni4WuDPU48QCNxBiW7bNHV63Dpn0FNISCphhjEVmR7LYY2Ie4IB1ZBsxLvoMKaAzhP/escQWsxip3aCldYCSnFk6YJMNwNamJsQsGLJZOj6jeJEz2AyNqbe0J27BKH9hEkUS58VFNfvWCw79L1Mby0CIkqefZ63lPjXrqLZBy+6pc+JDj4VTC5TRRGEymQLuJAzRmFCUfgfhEqg/Cv+ZfNCDRgl9BYx0CWVU9KWafz4/VrlzhnLPNxhYU3ky+H9kxKZ2VBRNT8aLTXfHqtIQGe0WlRO1SokSQ8n0fyU3kdPHFhLu09tpG0lhmw/+u3i0mXJ8KhYCaMID51z4gBkI3nzemCeDHVkDOFIgPgUSekEzb3Mi0NupxbFjwNt1Dj8QI9mmI8AZUe94AlpJFVaRPmPoOffkm5+Z38Y9+fsC+wRy5qBwFkKZ9pP1rsrOEqcZd7K/Z39CQPQIAI9nAOOKjcmP3DV1h5JQWLElhintdG7IsW/TnNiAXtBrd0F+qKOkCd2dRvCwdLTuvW02R3cFgMyGq9HpuR8M2Bo3O2JdULWC+SFsLxoQ="
before_script:
- "./Tools/before_install.sh"
script:
- "./Tools/gendocs.sh"
deploy:
  provider: releases
  api_key:
    secure: QLai/R0u3HbAtZAxZ+fgnsGf34aTuEHdkgDrYkNDRiPPKQYsYXgMalR6X4HoRDgas+HKSCYKBtt6qVfvlJbrYd2zRTeGtxNcdKY4eDkbxdWmjLWu4SwSgKbMOHSLAChUmZ4WS6a83g3wAL4s71nYmxyHqfYh99puJkohfZhQdg/RdpPT6qOMvS8uPp6wjrgzySRH0AOSH48l4VWrOnMkElb8FT/rjPJi9XkdfwyZkUVRIQ5LMij/zGfrlAT5dwMab4ONyYXCtMAv4jOEuR94V+dxm+I/V+CSPHwPXg62yOZDsNnl2p6/106raT1MHqy8f7QbLiXezeOmXINHPvkfndeYLm9o2aErIs9xCBYUqWHKj70WOBeog9+H42EvGybN5yek0XJfP5HzjkPgf30WQoptd+rnC4THQlUJ5RlOT8Lwb9NdUO/fuZnkBUowYmGVU3G8+iQMJcG0gkqwR20rOOHeZ+B+Aknq6mZo4g+5Gzl3XpM7D+x87+rXEJ1BRJn7HR/uOkEgV1rMG67vQrhso6Ve400EQ96or+cU5ZvreS3JpXtW49xd2QImgwJvQ8LcSqubZiqXQ+UW+9+C4imkswSVbAK5KPnv06vmOrDSr1x+JWGRx13ma7UOcQtxgkKwbD35/HVPtXL/J27LMZx8iOtkSHcQ7aCkmezpvCYo3Rk=
  file:
    - "$TRAVIS_BUILD_DIR/generated/OWASP_Mobile_AppSec_Verification_Standard_${TRAVIS_TAG}_Document.pdf"
    - "$TRAVIS_BUILD_DIR/generated/OWASP_Mobile_AppSec_Verification_Standard_${TRAVIS_TAG}_Document-es.pdf"
    - "$TRAVIS_BUILD_DIR/generated/OWASP_Mobile_AppSec_Verification_Standard_${TRAVIS_TAG}_Document-fr.pdf"
    - "$TRAVIS_BUILD_DIR/generated/OWASP_Mobile_AppSec_Verification_Standard_${TRAVIS_TAG}_Document-de.pdf"
    - "$TRAVIS_BUILD_DIR/generated/OWASP_Mobile_AppSec_Verification_Standard_${TRAVIS_TAG}_Document-ja.pdf"
    - "$TRAVIS_BUILD_DIR/generated/OWASP_Mobile_AppSec_Verification_Standard_${TRAVIS_TAG}_Document-ru.pdf"
    - "$TRAVIS_BUILD_DIR/generated/OWASP_Mobile_AppSec_Verification_Standard_${TRAVIS_TAG}_Document-zhtw.pdf"
    - "$TRAVIS_BUILD_DIR/generated/OWASP_Mobile_AppSec_Verification_Standard_${TRAVIS_TAG}_Document.mobi"
    - "$TRAVIS_BUILD_DIR/generated/OWASP_Mobile_AppSec_Verification_Standard_${TRAVIS_TAG}_Document-es.mobi"
    - "$TRAVIS_BUILD_DIR/generated/OWASP_Mobile_AppSec_Verification_Standard_${TRAVIS_TAG}_Document-fr.mobi"
    - "$TRAVIS_BUILD_DIR/generated/OWASP_Mobile_AppSec_Verification_Standard_${TRAVIS_TAG}_Document-de.mobi"
    - "$TRAVIS_BUILD_DIR/generated/OWASP_Mobile_AppSec_Verification_Standard_${TRAVIS_TAG}_Document-ja.mobi"
    - "$TRAVIS_BUILD_DIR/generated/OWASP_Mobile_AppSec_Verification_Standard_${TRAVIS_TAG}_Document-ru.mobi"
    - "$TRAVIS_BUILD_DIR/generated/OWASP_Mobile_AppSec_Verification_Standard_${TRAVIS_TAG}_Document-zhtw.mobi"
    - "$TRAVIS_BUILD_DIR/generated/OWASP_Mobile_AppSec_Verification_Standard_${TRAVIS_TAG}_Document.epub"
    - "$TRAVIS_BUILD_DIR/generated/OWASP_Mobile_AppSec_Verification_Standard_${TRAVIS_TAG}_Document-ru.epub"
    - "$TRAVIS_BUILD_DIR/generated/OWASP_Mobile_AppSec_Verification_Standard_${TRAVIS_TAG}_Document-es.epub"
    - "$TRAVIS_BUILD_DIR/generated/OWASP_Mobile_AppSec_Verification_Standard_${TRAVIS_TAG}_Document-fr.epub"
    - "$TRAVIS_BUILD_DIR/generated/OWASP_Mobile_AppSec_Verification_Standard_${TRAVIS_TAG}_Document-de.epub"
    - "$TRAVIS_BUILD_DIR/generated/OWASP_Mobile_AppSec_Verification_Standard_${TRAVIS_TAG}_Document-ja.epub"
    - "$TRAVIS_BUILD_DIR/generated/OWASP_Mobile_AppSec_Verification_Standard_${TRAVIS_TAG}_Document-zhtw.epub"
    - "$TRAVIS_BUILD_DIR/generated/MASVS.docx"
    - "$TRAVIS_BUILD_DIR/generated/MASVS-de.docx"
    - "$TRAVIS_BUILD_DIR/generated/MASVS-es.docx"
    - "$TRAVIS_BUILD_DIR/generated/MASVS-fr.docx"
    - "$TRAVIS_BUILD_DIR/generated/MASVS-ja.docx"
    - "$TRAVIS_BUILD_DIR/generated/MASVS-ru.docx"
    - "$TRAVIS_BUILD_DIR/generated/MASVS-zhtw.docx"
  skip_cleanup: true
  overwrite: true
  name: "Intermediate update ${TRAVIS_TAG}"
  body: "Intermediate update (${TRAVIS_TAG}). See CHANGELOG.md for updates on intermediate update releases."
  on:
    repo: OWASP/owasp-masvs
    tags: true
