sudo: required
language: objective-c
osx_image: xcode9.3
before_install:
- rvm install 2.5.1 --disable-binary
- brew install pandoc
- brew cask install calibre
- npm install -g gitbook-cli
- gem install asciidoctor
script:
- "./Tools/gendocs.sh"
deploy:
  provider: releases
  api_key:
    secure: iWqrxeI6PIoqeRqjikeeySNKbtbhrX4hdg1Nj8pPKc/WvkfPO3vC6BGoHNtDeNao7bCuv8trqgwsF9XLOYQzjYpqKFuKI0YFE78hDW0Uv+I25GGc474n9goGX4a/3bPR6nmwcDrh2Ng6Z5sPwVNufOjgcs/uXj6u3U0IYHEvgQOUGUwq4pBUTOM+hvo2687ekap6vPBifDkKHTf/65MRH3E1UOBe3zH0d/D3CiEgKf/i/eSgOIixedk8PGvlBVGc1WJb9+sweXZL5eXLBjbrzDogfAC8JWnTEu9050oCdyZCMndGviprMDU/EOZL06pQaPSBHXfFEH5pcG6wlF21VPEsjSN0y4YLSuM+Ukr22Gca51LPXiqn6M/kO5lJvERruUfSV4oD+dKKxuaGGHBMu8+53tHDCNmnrRF6YKTaTSOzBtWtB/ocMYTxtJ2++SUc/seKt4tcAmMbr4N+Ta5HptHd2CaN5Dhd7P06wM5R2JNmgw9N/YqwWu87FhXNRCqApbOtlO7ejHofjgaJi4V/vya6zbx7hl/jOeOg2jJ8phw3F0DwMgiKinA2d6o8A3AxyONw3cZone0XAUYGFMpu/BkRt7DDFV8sW/p07/hZLD6kgjNyyzn21W4oZa/JC8E9Uez4aaUrbRePzbYzmkhX5EB0FE2piEYNSlYZby3dDEw=
  file:
    - "$TRAVIS_BUILD_DIR/Generated/OWASP_Mobile_AppSec_Verification_Standard_$TRAVIS_TAG_Document.pdf"
    - "$TRAVIS_BUILD_DIR/Generated/OWASP_Mobile_AppSec_Verification_Standard_$TRAVIS_TAG_Document-es.pdf"
    - "$TRAVIS_BUILD_DIR/Generated/OWASP_Mobile_AppSec_Verification_Standard_$TRAVIS_TAG_Document-fr.pdf"
    - "$TRAVIS_BUILD_DIR/Generated/OWASP_Mobile_AppSec_Verification_Standard_$TRAVIS_TAG_Document-de.pdf"
    - "$TRAVIS_BUILD_DIR/Generated/OWASP_Mobile_AppSec_Verification_Standard_$TRAVIS_TAG_Document-ja.pdf"
    - "$TRAVIS_BUILD_DIR/Generated/OWASP_Mobile_AppSec_Verification_Standard_$TRAVIS_TAG_Document-ru.pdf"
    - "$TRAVIS_BUILD_DIR/Generated/OWASP_Mobile_AppSec_Verification_Standard_$TRAVIS_TAG_Document-zhtw.pdf"
    - "$TRAVIS_BUILD_DIR/Generated/OWASP_Mobile_AppSec_Verification_Standard_$TRAVIS_TAG_Document.mobi"
    - "$TRAVIS_BUILD_DIR/Generated/OWASP_Mobile_AppSec_Verification_Standard_$TRAVIS_TAG_Document-es.mobi"
    - "$TRAVIS_BUILD_DIR/Generated/OWASP_Mobile_AppSec_Verification_Standard_$TRAVIS_TAG_Document-fr.mobi"
    - "$TRAVIS_BUILD_DIR/Generated/OWASP_Mobile_AppSec_Verification_Standard_$TRAVIS_TAG_Document-de.mobi"
    - "$TRAVIS_BUILD_DIR/Generated/OWASP_Mobile_AppSec_Verification_Standard_$TRAVIS_TAG_Document-ja.mobi"
    - "$TRAVIS_BUILD_DIR/Generated/OWASP_Mobile_AppSec_Verification_Standard_$TRAVIS_TAG_Document-ru.mobi"
    - "$TRAVIS_BUILD_DIR/Generated/OWASP_Mobile_AppSec_Verification_Standard_$TRAVIS_TAG_Document-zhtw.mobi"
    - "$TRAVIS_BUILD_DIR/Generated/OWASP_Mobile_AppSec_Verification_Standard_$TRAVIS_TAG_Document.epub"
    - "$TRAVIS_BUILD_DIR/Generated/OWASP_Mobile_AppSec_Verification_Standard_$TRAVIS_TAG_Document-ru.epub"
    - "$TRAVIS_BUILD_DIR/Generated/OWASP_Mobile_AppSec_Verification_Standard_$TRAVIS_TAG_Document-es.epub"
    - "$TRAVIS_BUILD_DIR/Generated/OWASP_Mobile_AppSec_Verification_Standard_$TRAVIS_TAG_Document-fr.epub"
    - "$TRAVIS_BUILD_DIR/Generated/OWASP_Mobile_AppSec_Verification_Standard_$TRAVIS_TAG_Document-de.epub"
    - "$TRAVIS_BUILD_DIR/Generated/OWASP_Mobile_AppSec_Verification_Standard_$TRAVIS_TAG_Document-ja.epub"
    - "$TRAVIS_BUILD_DIR/Generated/OWASP_Mobile_AppSec_Verification_Standard_$TRAVIS_TAG_Document-zhtw.epub"
    - "$TRAVIS_BUILD_DIR/Generated/MASVS.docx"
    - "$TRAVIS_BUILD_DIR/Generated/MASVS-de.docx"
    - "$TRAVIS_BUILD_DIR/Generated/MASVS-es.docx"
    - "$TRAVIS_BUILD_DIR/Generated/MASVS-fr.docx"
    - "$TRAVIS_BUILD_DIR/Generated/MASVS-ja.docx"
    - "$TRAVIS_BUILD_DIR/Generated/MASVS-ru.docx"
    - "$TRAVIS_BUILD_DIR/Generated/MASVS-zhtw.docx"
  skip_cleanup: true
  overwrite: true
  name: "Intermediate update $TRAVIS_TAG"
  body: "Intermediate update ($TRAVIS_TAG). See CHANGELOG.md for updates on intermediate update releases."
  on:
    repo: OWASP/owasp-masvs
    tags: true
