name: Check Markdown links

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: link-check
        uses: gaurav-nelson/github-action-markdown-link-check@0.4.0
