name: Check Markdown links

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: link-check
        uses: gaurav-nelson/github-action-markdown-link-check@0.4.0
# todo: add suppression as noted at https://github.com/marketplace/actions/markdown-link-check
  markdown-lint-check:
    runs-on: ubuntu-latest
    steps:
      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: .
          config_file: ".markdownlint.yaml"
          ignore_files: "examples/ignore/*"
          rules: "examples/rules/custom.js"
# todo: fix configuration