# https://docs.github.com/en/actions/learn-github-actions/reusing-workflows

on:
  workflow_call:
    inputs:
      language:         # English, German, Spanish, etc.
        required: true
        type: string
      lang:   # en, de, es , etc.
        required: true
        type: string
      folder:
        required: true
        type: string
      version:
        required: true
        type: string
      pandocker-tag:
        required: false
        type: string
      pandocker-template:
        required: false
        type: string


jobs:
  doc-gen-reusable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Get previous tag
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"

    - name: Set VERSION to local job env
      run: echo "VERSION=${{ steps.previoustag.outputs.tag }}" >> $GITHUB_ENV

    - name: Generate ${{ inputs.language }} PDF
      run: ${{ inputs.pandocker-tag }} ${{ inputs.pandocker-template }} ./tools/docker/pandoc_makedocs.sh ${{ inputs.folder }} ${{ env.VERSION }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-${{ env.VERSION }}-${{ inputs.lang }}
        path: OWASP_MASVS-${{ env.VERSION }}-${{ inputs.lang }}*
