# https://docs.github.com/en/actions/learn-github-actions/reusing-workflows

on:
  workflow_call:
    inputs:
      language:         # English, German, Spanish, etc.
        required: true
        type: string
      lang:   # en, de, es , etc.
        required: true
        type: string
      folder:
        required: true
        type: string
      version:
        required: true
        type: string
      pandocker-tag:
        required: false
        type: string
      pandocker-template:
        required: false
        type: string


jobs:
  doc-gen-reusable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: get ref in reusable
      run: echo ${{ github.ref_name }}

    - name: Set DOC_VERSION to env
      run: echo "DOC_VERSION=$(echo ${{ github.ref_name }} | cut -c 1-6)" >> $GITHUB_ENV

    - name: Generate ${{ inputs.language }} PDF
      run: ${{ inputs.pandocker-tag }} ${{ inputs.pandocker-template }} ./tools/docker/pandoc_makedocs.sh ${{ inputs.folder }} $DOC_VERSION

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: OWASP_MASVS-$DOC_VERSION-${{ inputs.lang }}
        path: OWASP_MASVS-$DOC_VERSION-${{ inputs.lang }}*
