name: CI Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Build the Docker image
      run: docker build ./tools/docker --tag masvs-generator:latest

    - name: Generate python scripts (csv)
      run: docker run -v ${PWD}:/documents masvs-generator 'cd /documents/tools && python3 export.py --format csv --lang en > OWASP_MASVS-SNAPSHOT.csv'
    - name: Generate python scripts (json)
      run: docker run -v ${PWD}:/documents masvs-generator 'cd /documents/tools && python3 export.py --format json --lang en > OWASP_MASVS-SNAPSHOT.json'
    - name: Generate python scripts (xml)
      run: docker run -v ${PWD}:/documents masvs-generator 'cd /documents/tools && python3 export.py --format xml --lang en > OWASP_MASVS-SNAPSHOT.xml'
    
    - name: Upload CSV export
      uses: actions/upload-artifact@v1
      with:
        name: OWASP_MASVS-SNAPSHOT.csv
        path: tools/OWASP_MASVS-SNAPSHOT.csv
    - name: Upload JSON export
      uses: actions/upload-artifact@v1
      with:
        name: OWASP_MASVS-SNAPSHOT.json
        path: tools/OWASP_MASVS-SNAPSHOT.json
    - name: Upload XML export
      uses: actions/upload-artifact@v1
      with:
        name: OWASP_MASVS-SNAPSHOT.xml
        path: tools/OWASP_MASVS-SNAPSHOT.xml
    
    - name: Generate English PDF
      run: docker run --rm -u `id -u`:`id -g` -v ${PWD}:/pandoc masvs-generator '/pandoc_makedocs.sh Document 1.2'
    - name: Upload English PDF
      uses: actions/upload-artifact@v1
      with:
        name: OWASP_MASVS-SNAPSHOT-en.pdf
        path: OWASP_MASVS-SNAPSHOT-en.pdf
    - name: Upload English EPUB
      uses: actions/upload-artifact@v1
      with:
        name: OWASP_MASVS-SNAPSHOT-en.epub
        path: OWASP_MASVS-SNAPSHOT-en.epub
    - name: Upload English DOCX
      uses: actions/upload-artifact@v1
      with:
        name: OWASP_MASVS-SNAPSHOT-en.docx
        path: OWASP_MASVS-SNAPSHOT-en.docx

    - name: Generate Spanish PDF
      run: docker run --rm -u `id -u`:`id -g` -v ${PWD}:/pandoc masvs-generator '/pandoc_makedocs.sh Document-es 1.2'
    - name: Upload Spanish PDF
      uses: actions/upload-artifact@v1
      with:
        name: OWASP_MASVS-SNAPSHOT-es.pdf
        path: OWASP_MASVS-SNAPSHOT-es.pdf
    - name: Upload Spanish EPUB
      uses: actions/upload-artifact@v1
      with:
        name: OWASP_MASVS-SNAPSHOT-es.epub
        path: OWASP_MASVS-SNAPSHOT-es.epub

    - name: Generate German PDF
      run: docker run --rm -u `id -u`:`id -g` -v ${PWD}:/pandoc masvs-generator '/pandoc_makedocs.sh Document-de 1.2'
    - name: Upload German PDF
      uses: actions/upload-artifact@v1
      with:
        name: OWASP_MASVS-SNAPSHOT-de.pdf
        path: OWASP_MASVS-SNAPSHOT-de.pdf
    - name: Upload German EPUB
      uses: actions/upload-artifact@v1
      with:
        name: OWASP_MASVS-SNAPSHOT-de.epub
        path: OWASP_MASVS-SNAPSHOT-de.epub

    - name: Generate French PDF
      run: docker run --rm -u `id -u`:`id -g` -v ${PWD}:/pandoc masvs-generator '/pandoc_makedocs.sh Document-fr 1.2'
    - name: Upload French PDF
      uses: actions/upload-artifact@v1
      with:
        name: OWASP_MASVS-SNAPSHOT-fr.pdf
        path: OWASP_MASVS-SNAPSHOT-fr.pdf
    - name: Upload French EPUB
      uses: actions/upload-artifact@v1
      with:
        name: OWASP_MASVS-SNAPSHOT-fr.epub
        path: OWASP_MASVS-SNAPSHOT-fr.epub

    - name: Generate Russian PDF
      run: docker run --rm -u `id -u`:`id -g` -v ${PWD}:/pandoc masvs-generator '/pandoc_makedocs.sh Document-ru 1.2'
    - name: Upload Russian PDF
      uses: actions/upload-artifact@v1
      with:
        name: OWASP_MASVS-SNAPSHOT-ru.pdf
        path: OWASP_MASVS-SNAPSHOT-ru.pdf
    - name: Upload Russian EPUB
      uses: actions/upload-artifact@v1
      with:
        name: OWASP_MASVS-SNAPSHOT-ru.epub
        path: OWASP_MASVS-SNAPSHOT-ru.epub

    - name: Generate Japanese PDF
      run: docker run --rm -u `id -u`:`id -g` -v ${PWD}:/pandoc masvs-generator '/pandoc_makedocs.sh Document-ja 1.2'
    - name: Upload Japanese PDF
      uses: actions/upload-artifact@v1
      with:
        name: OWASP_MASVS-SNAPSHOT-ja.pdf
        path: OWASP_MASVS-SNAPSHOT-ja.pdf
    - name: Upload Japanese EPUB
      uses: actions/upload-artifact@v1
      with:
        name: OWASP_MASVS-SNAPSHOT-ja.epub
        path: OWASP_MASVS-SNAPSHOT-ja.epub
    
    - name: Generate Traditional Chinese PDF
      run: docker run --rm -u `id -u`:`id -g` -v ${PWD}:/pandoc masvs-generator '/pandoc_makedocs.sh Document-zhtw 1.2'
    - name: Upload Traditional Chinese PDF
      uses: actions/upload-artifact@v1
      with:
        name: OWASP_MASVS-SNAPSHOT-zhtw.pdf
        path: OWASP_MASVS-SNAPSHOT-zhtw.pdf
    - name: Upload Traditional Chinese EPUB
      uses: actions/upload-artifact@v1
      with:
        name: OWASP_MASVS-SNAPSHOT-zhtw.epub
        path: OWASP_MASVS-SNAPSHOT-zhtw.epub

    - name: Generate Simplified Chinese PDF
      run: docker run --rm -u `id -u`:`id -g` -v ${PWD}:/pandoc masvs-generator '/pandoc_makedocs.sh Document-zhcn 1.2'
    - name: Upload Simplified Chinese PDF
      uses: actions/upload-artifact@v1
      with:
        name: OWASP_MASVS-SNAPSHOT-zhcn.pdf
        path: OWASP_MASVS-SNAPSHOT-zhcn.pdf
    - name: Upload Simplified Chinese EPUB
      uses: actions/upload-artifact@v1
      with:
        name: OWASP_MASVS-SNAPSHOT-zhcn.epub
        path: OWASP_MASVS-SNAPSHOT-zhcn.epub

    - name: Generate Korean PDF
      run: docker run --rm -u `id -u`:`id -g` -v ${PWD}:/pandoc masvs-generator '/pandoc_makedocs.sh Document-ko 1.2'
    - name: Upload Korean PDF
      uses: actions/upload-artifact@v1
      with:
        name: OWASP_MASVS-SNAPSHOT-ko.pdf
        path: OWASP_MASVS-SNAPSHOT-ko.pdf
    - name: Upload Korean EPUB
      uses: actions/upload-artifact@v1
      with:
        name: OWASP_MASVS-SNAPSHOT-ko.epub
        path: OWASP_MASVS-SNAPSHOT-ko.epub