name: Check Markdown links

on: push

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: link-check
        uses: gaurav-nelson/github-action-markdown-link-check@0.4.0
